version: '3.7'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: kaue
      DATABASE_PASSWORD: 123
      DATABASE_NAME: database_application
    volumes:
      - .:/app
    
  db:
    image: mysql:8.0.38  
    container_name: mysql_test  
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: database_application
      MYSQL_USER: kaue
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
