version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_USER: kaue
      MYSQL_PASSWORD: 123
      MYSQL_HOST: db
      MYSQL_DB: blog_data

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: blog_data
      MYSQL_USER: kaue
      MYSQL_PASSWORD: 123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
